backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets
collections:
  - label: 'Settings'
    name: 'settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'src/settings/general.md'
        label: 'General Setting'
        name: 'general'
        delete: false
        description: 'General Site Settings'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'general_setting', required: true, }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'General Setting', required: true, }
          - { label: 'Body', name: 'body', widget: 'string' }
      - file: 'src/settings/slug.md'
        label: 'URL Redirect'
        name: 'slug'
        delete: false
        description: 'Creates URL Redirector'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'slug_setting', required: true, }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'URL Redirect', required: true, }
          - name: 'redirect'
            label: 'URL LIST'
            widget: 'list'
            label_singular: 'Redirect'
            required: false
            fields:
              - { label: 'From (Internal Slug)', name: 'from', widget: 'string',
                  hint: 'Lower Characters (a-z), Numericals (0-9), dash (-), forwardslash (/) and must not start with a /, Minimum 3 Characters, eg: "redirect-to-google"',
                  pattern: [
                    [
                      '^([a-z0-9]+(?:(-|/)[a-z0-9]+)*){3,}$',
                      'Invalid Characters'
                    ],]
                  }
              - { label: 'To', name: 'to', widget: 'string',
                  hint: 'Lower Characters (a-z), Numericals (0-9), dash (-), forwardslash (/) and must not start with a /, Minimum 3 Characters, eg: External URL "https://google.com", Internal: "google"',
                  pattern: [
                  [
                    '^([a-z0-9]+(?:(-|/)[a-z0-9]+)*){3,}$',
                      'Invalid Characters'
                  ],] }
              - { label: 'Active', name: 'status', widget: 'boolean', default: false }
